name: Test a docker image
on: push
jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Create a container on ubuntu
            run: docker run hello-world
    